version: 0.2

env:
  variables:
    PROJECT: BlazorX
    DOTNET_CORE_RUNTIME: 8.0

phases:
  install:
    runtime-versions:
      dotnet: ${DOTNET_CORE_RUNTIME}
  
  pre_build:
    commands:
      - dotnet restore
  
  build:
    commands:
      - dotnet build -c Release
#      - dotnet test -c Release --logger trx --results-directory ./testresults
  
  post_build:
    commands:
      - dotnet publish -c Release -o ./build_output ./${PROJECT}/${PROJECT}.csproj --self-contained false

artifacts:
  files:
    - '**/*'
  base-directory: ./build_output
  discard-paths: now

#reports:
#  ${PROJECT}:
#    file-format: VisualStudioTrx
#    files:
#      - '**/*'
#    base-directory: ./testresults'